### ISSUE TITLE
Register web domain

### ISSUE THREAD

**Issue by ArneBachmann** [ArneBachmann/sos#109]

**Comment by ArneBachmann** [comment]
http://sos-vcs.net

**Comment by ArneBachmann** [comment]
Yeah I stopped paying for the web domain once I couldn't invest time anymore into the project.
I still use SOS daily, but there are some bugs, and the code structure has reached unmaintainability.

**Comment by lispstudent** [comment]
Thank you for clarifying.

Would you consider asking on the [dev list](https://subversion.apache.org/mailing-lists.html)  if somebody would wish to either help maintaining  your sos app, or even integrating it into the extra subversion tools ? It is very useful indeed.
